from typing import Final

__all__ = [
    "STARTING_STARS",
    "STARTING_BANK",
    "BANKING_DEPOSIT_COOLDOWN_MINUTES",
    "BANKING_WITHDRAW_COOLDOWN_MINUTES",
]

STARTING_STARS: Final[int] = 0
STARTING_BANK: Final[int] = 0

BANKING_DEPOSIT_COOLDOWN_MINUTES = 60
BANKING_WITHDRAW_COOLDOWN_MINUTES = 15
