from typing import Final

__all__ = [
    "STARTING_STARS",
    "STARTING_BANK",
    "BANKING_DEPOSIT_COOLDOWN_MINUTES",
    "BANKING_WITHDRAW_COOLDOWN_MINUTES",
    "ACHIEVEMENT_DEFS",
]

STARTING_STARS: Final[int] = 0
STARTING_BANK: Final[int] = 0

BANKING_DEPOSIT_COOLDOWN_MINUTES = 60
BANKING_WITHDRAW_COOLDOWN_MINUTES = 15

ACHIEVEMENT_DEFS = (
    {
        "key": "first_star",
        "name": "First Star",
        "emoji": "⭐",
        "description": "Own at least 1 total star.",
    },
    {
        "key": "baby_saver",
        "name": "Baby Saver",
        "emoji": "🏦",
        "description": "Keep at least 1000 stars in the bank.",
    },
    {
        "key": "small_saver",
        "name": "Small Saver",
        "emoji": "🏦",
        "description": "Keep at least 5000 stars in the bank.",
    },
    {
        "key": "medium_saver",
        "name": "Medium Saver",
        "emoji": "🏦",
        "description": "Keep at least 10000 stars in the bank.",
    },
    {
        "key": "miner_upgrade",
        "name": "Miner Upgrade",
        "emoji": "⛏️",
        "description": "Reach mine level 5.",
    },
    {
        "key": "prepared_miner",
        "name": "Prepared Miner",
        "emoji": "🛡️",
        "description": "Own both a helmet and a sword.",
    },
    {
        "key": "tool_owner",
        "name": "Tool Owner",
        "emoji": "✨",
        "description": "Own either a Gold Pickaxe or Telescope.",
    },
    {
        "key": "space_ready",
        "name": "Space Ready",
        "emoji": "🚀",
        "description": "Own a Rocket Ship.",
    },
    {
        "key": "budding_farmer",
        "name": "Budding Farmer",
        "emoji": "🌱",
        "description": "Buy your first farm plot.",
    },
    {
        "key": "land_baron",
        "name": "Land Baron",
        "emoji": "🏡",
        "description": "Own all farm plots.",
    },
    {
        "key": "master_farmer",
        "name": "Master Farmer",
        "emoji": "🌾",
        "description": "Upgrade your farm to max level.",
    },
    {
        "key": "sun_blessed",
        "name": "Sun Blessed",
        "emoji": "🌤️",
        "description": "Receive a Perfect Weather event.",
        "progress_key": "weather_perfect_events",
        "target": 1,
    },
    {
        "key": "storm_touched",
        "name": "Storm Touched",
        "emoji": "🍂",
        "description": "Receive a bad weather event.",
        "progress_key": "weather_bad_events",
        "target": 1,
    },
    {
        "key": "farming_10k_harvest",
        "name": "Field Investor",
        "emoji": "🧺",
        "description": "Earn 10,000 stars from farm harvests.",
        "progress_key": "farming_harvest_stars_earned",
        "target": 10000,
    },
    {
        "key": "farming_100k_harvest",
        "name": "Harvest Tycoon",
        "emoji": "🌾",
        "description": "Earn 100,000 stars from farm harvests.",
        "progress_key": "farming_harvest_stars_earned",
        "target": 100000,
    },
    {
        "key": "farm_tender_10",
        "name": "Soil Steward",
        "emoji": "🧪",
        "description": "Tend your plots 10 times.",
        "progress_key": "farming_tends",
        "target": 10,
    },
    {
        "key": "farm_tender_100",
        "name": "Garden Caretaker",
        "emoji": "💧",
        "description": "Tend your plots 100 times.",
        "progress_key": "farming_tends",
        "target": 100,
    },
    {
        "key": "crop_rotator_25",
        "name": "Crop Rotator",
        "emoji": "🔄",
        "description": "Rotate crops on the same plot 25 times.",
        "progress_key": "farming_crop_rotations",
        "target": 25,
    },
    {
        "key": "crop_rotator_100",
        "name": "Rotation Master",
        "emoji": "♻️",
        "description": "Rotate crops on the same plot 100 times.",
        "progress_key": "farming_crop_rotations",
        "target": 100,
    },
    {
        "key": "mine_100",
        "name": "Centurion Miner",
        "emoji": "💎",
        "description": "Mine 100 times total.",
        "progress_key": "mine_runs",
        "target": 100,
    },
    {
        "key": "mine_1000",
        "name": "Mining Legend",
        "emoji": "👑",
        "description": "Mine 1000 times total.",
        "progress_key": "mine_runs",
        "target": 1000,
    },
    {
        "key": "fish_10",
        "name": "Lake Regular",
        "emoji": "🐟",
        "description": "Catch 10 fish total.",
        "progress_key": "fish_catches",
        "target": 10,
    },
    {
        "key": "fish_100",
        "name": "Ocean Veteran",
        "emoji": "🐠",
        "description": "Catch 100 fish total.",
        "progress_key": "fish_catches",
        "target": 100,
    },
    {
        "key": "fish_too_early",
        "name": "Too Eager",
        "emoji": "🎣",
        "description": "Pull your line too early once.",
        "progress_key": "fish_early_pulls",
        "target": 1,
    },
    {
        "key": "gambling_lost_1000",
        "name": "House Favorite",
        "emoji": "🎲",
        "description": "Lose 1000 stars total from gambling.",
        "progress_key": "gambling_stars_lost",
        "target": 1000,
    },
    {
        "key": "gambling_won_1000",
        "name": "High Roller",
        "emoji": "🃏",
        "description": "Win 1000 stars total from gambling.",
        "progress_key": "gambling_stars_won",
        "target": 1000,
    },
    {
        "key": "duel_first_blood",
        "name": "First Blood Oath",
        "emoji": "⚔️",
        "description": "Win your first duel.",
        "progress_key": "duel_wins",
        "target": 1,
    },
    {
        "key": "duel_warlord",
        "name": "Dueling Warlord",
        "emoji": "🛡️",
        "description": "Win 50 duels.",
        "progress_key": "duel_wins",
        "target": 50,
    },
    {
        "key": "roulette_survivor",
        "name": "Chamber Whisperer",
        "emoji": "🔫",
        "description": "Win a game of Russian roulette.",
        "progress_key": "roulette_wins",
        "target": 1,
    },
    {
        "key": "roulette_fall_guy",
        "name": "Bullet Magnet",
        "emoji": "💀",
        "description": "Die from Russian roulette once.",
        "progress_key": "roulette_deaths",
        "target": 1,
    },
    {
        "key": "roulette_legend",
        "name": "Last Chamber Legend",
        "emoji": "🧨",
        "description": "Win Russian roulette 10 times.",
        "progress_key": "roulette_wins",
        "target": 10,
    },
)
